# Use an official Node.js runtime as a parent image
FROM node:14

# Set the working directory in the container
WORKDIR /app

# Copy the package.json and package-lock.json files to the container
COPY ./package*.json ./

# Install frontend dependencies
RUN npm install

# Copy the rest of the frontend application code to the container
COPY ./ .

# Expose port 80 for serving the frontend
EXPOSE 5173:5173

# Define the command to start the frontend server
CMD ["npm", "run", "dev", "--", "--host"]
