version: '3.8'
services: 
  mongodb:
    image: mongo
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    ports:
      - "27017:27017"

  fastapi:
    image: salehoh/mosaic-backend:1.0
    volumes:
      - data-volume:/var/www/data
    depends_on:
      - mongodb

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - data-volume:/var/www/data
    depends_on:
      - fastapi

volumes:
  data-volume:
  mongodb_data:
