import type { Samples } from "./types";

export const mockSample: Samples[] = [
    {
        Sample: "BrainTissueSample1",
        Sample_ID: "BT1",
        SampleGroup: "Neurology",
        Description: "Sample from patient with Alzheimer's",
        Organism: "Homo sapiens",
        Tissue: "Brain",
        Sex: "Male",
        Cell_Line: "BT474",
        Mouse_Model: "ModelBT1",
        Biomaterial_Provider: "BioLab1",
        Date_Sample_Prep: "2022-01-01",
        Biological_Repeat: "Repeat1",
        Disease_State: "Alzheimer's",
        Age: "78",
    },
    {
        Sample: "LiverTissueSample1",
        Sample_ID: "LT1",
        SampleGroup: "Hepatology",
        Description: "Sample from patient with Hepatitis C",
        Organism: "Homo sapiens",
        Tissue: "Liver",
        Sex: "Female",
        Cell_Line: "HepG2",
        Mouse_Model: "ModelLT1",
        Biomaterial_Provider: "BioLab2",
        Date_Sample_Prep: "2022-02-02",
        Biological_Repeat: "Repeat2",
        Disease_State: "Hepatitis C",
        Age: "52",
    },
    {
        Sample: "HeartTissueSample1",
        Sample_ID: "HT1",
        SampleGroup: "Cardiology",
        Description: "Sample from patient with Heart Disease",
        Organism: "Homo sapiens",
        Tissue: "Heart",
        Sex: "Male",
        Cell_Line: "AC16",
        Mouse_Model: "ModelHT1",
        Biomaterial_Provider: "BioLab3",
        Date_Sample_Prep: "2022-03-03",
        Biological_Repeat: "Repeat3",
        Disease_State: "Heart Disease",
        Age: "65",
    },
    {
        Sample: "LungTissueSample1",
        Sample_ID: "LgT1",
        SampleGroup: "Pulmonology",
        Description: "Sample from patient with Lung Cancer",
        Organism: "Homo sapiens",
        Tissue: "Lung",
        Sex: "Female",
        Cell_Line: "A549",
        Mouse_Model: "ModelLgT1",
        Biomaterial_Provider: "BioLab4",
        Date_Sample_Prep: "2022-04-04",
        Biological_Repeat: "Repeat4",
        Disease_State: "Lung Cancer",
        Age: "70",
    },
];