export type SampleType = {
  assayName: string;
  organism: string;
  strain: string;
  individual: string;
  age: string;
  developmentalStage: string;
  sex: string;
  organismPart: string;
  cellType?: string;
  genotype: string;
  [key: string]: any; // Allow additional properties
};

export type SearchItemType = {
    accession: string;
    authors: string[];
    title: string;
    studyType: string;
    organism: string;
    description: string;
    releaseDate: string;
    samplesCount: number;
    technology? : string;
    assayByMolecule?: string;
    experimentalDesigns?: string;
    experimentalFactors?: string;
    assayCount?: number;
    releaseLinks: string;
    releaseFiles?: string;
    releaseViews? : string;
    content?: string;

    samples: SampleType[];
    
};
export const data: SearchItemType[] = [
  {
    "accession": "E-MTAB-13360",
    "authors": ["Owen Dando"],
    "releaseDate": "11 22 2023",
    "organism": "Mus musculus",
    "studyType": "RNA-seq of coding RNA",
    "samplesCount": 10,
    "releaseLinks": "1 link",
    "releaseFiles": "2 files",
    "releaseViews": "3 views",
    "title": "RNA-seq to investigate sex-dependent changes in microglia in Cst7 knockout mice crossed with a mouse model of amyloid-driven Alzheimer's Disease",
    "description": "Microglial endolysosomal dysfunction is strongly implicated in neurodegeneration. Transcriptomic studies show that a microglial state characterised by a set of genes involved in endolysosomal function is induced in both mouse Alzheimer’s Disease (AD) models and in human AD brain, and that the onset of this state is emphasised in females. Cst7 (Cystatin F) is among the most highly unregulated genes in these microglia. However, the sex-specific function of Cst7 in neurodegenerative disease is not understood. Here, we crossed Cst7 -/- mice with the App NL-G-F mouse to test the role of Cst7 in a model of amyloid-driven AD.",
    "experimentalDesigns": "genotype design, sex design",
    "experimentalFactors": "Experimental Factors",
    "technology": "Sequencing assay",
    "assayByMolecule": "RNA assay",
    "assayCount": 18,
    "samples": [
      {
        assayName: "1_1",
        organism: "Mus musculus",
        strain: "C57Bl/6J",
        individual: "306/150",
        age: "12",
        developmentalStage: "adult",
        sex: "male",
        organismPart: "brain",
        cellType: "microglia",
        genotype: "Cst7 +/+, APP wt/wt"
    },
    {
        assayName: "1_2",
        organism: "Mus musculus",
        strain: "C57Bl/6J",
        individual: "202/299",
        age: "12",
        developmentalStage: "adult",
        sex: "male",
        organismPart: "brain",
        cellType: "microglia",
        genotype: "Cst7 +/+, APP wt/wt"
    },
    {
        assayName: "1_3",
        organism: "Mus musculus",
        strain: "C57Bl/6J",
        individual: "307",
        age: "12",
        developmentalStage: "adult",
        sex: "male",
        organismPart: "brain",
        cellType: "microglia",
        genotype: "Cst7 +/+, APP wt/wt"
    },
    {
        assayName: "2_1",
        organism: "Mus musculus",
        strain: "C57Bl/6J",
        individual: "284/301/300",
        age: "12",
        developmentalStage: "adult",
        sex: "female",
        organismPart: "brain",
        cellType: "microglia",
        genotype: "Cst7 +/+, APP wt/wt"
    },
    {
        assayName: "2_2",
        organism: "Mus musculus",
        strain: "C57Bl/6J",
        individual: "309/237/169",
        age: "12",
        developmentalStage: "adult",
        sex: "female",
        organismPart: "brain",
        cellType: "microglia",
        genotype: "Cst7 +/+, APP wt/wt"
    },
    {
        assayName: "2_3",
        organism: "Mus musculus",
        strain: "C57Bl/6J",
        individual: "308/283/302",
        age: "12",
        developmentalStage: "adult",
        sex: "female",
        organismPart: "brain",
        cellType: "microglia",
        genotype: "Cst7 +/+, APP wt/wt"
    },
    {
        assayName: "3_1",
        organism: "Mus musculus",
        strain: "C57Bl/6J",
        individual: "245/246/153/197",
        age: "12",
        developmentalStage: "adult",
        sex: "male",
        organismPart: "brain",
        cellType: "microglia",
        genotype: "Cst7 +/+, APP tg/tg"
    },
    {
        assayName: "3_2",
        organism: "Mus musculus",
        strain: "C57Bl/6J",
        individual: "293/319/294/278",
        age: "12",
        developmentalStage: "adult",
        sex: "male",
        organismPart: "brain",
        cellType: "microglia",
        genotype: "Cst7 +/+, APP tg/tg"
    },
    {
        assayName: "3_3",
        organism: "Mus musculus",
        strain: "C57Bl/6J",
        individual: "318/244/303/304",
        age: "12",
        developmentalStage: "adult",
        sex: "male",
        organismPart: "brain",
        cellType: "microglia",
        genotype: "Cst7 +/+, APP tg/tg"
    },
    {
        assayName: "4_1",
        organism: "Mus musculus",
        strain: "C57Bl/6J",
        individual: "279/322/296/295",
        age: "12",
        developmentalStage: "adult",
        sex: "female",
        organismPart: "brain",
        cellType: "microglia",
        genotype: "Cst7 +/+, APP tg/tg"
    }
  ]
  },
  {
    "accession": "E-MTAB-12454",
    "authors": [
      "Pablo Baeza Centurion",
      "Fritjof Lammers",
      "Mikaela Behm",
      "Michaela Frye",
      "Duncan Odom",
      "Angela Goncalves"
    ],
    "title": "Single-cell RNA (10X Chromium) of mouse DMBA/TPA treated or control back skin and matched livers (DKFZ) 2022",
    "studyType": "RNA-seq of coding RNA from single cells",
    "organism": "Mus musculus",
    "description": "We generated single cell transcriptomes from full thickness skin biopsies in mouse to quantify the skin cell types found in this species (control samples). To study how mouse skin changes upon exposure to a carcinogen, we performed a classical two-stage skin carcinogenesis experiment, wherein cancer is initiated by a single application of 7,12-dimethylbenz[a]-anthracene (DMBA) followed by repeated treatment with 12-O-tetradecanoylphorbol-13-acetate (TPA) to drive cell proliferation. After 10 weeks, full thickness skin biopsies were collected and used to generate single cell transcriptomes (treatment samples).",
    "releaseDate": "21 November 2023",
    "samplesCount": 32,
    "technology": "Sequencing assay",
    "assayByMolecule": "RNA assay",
    "experimentalDesigns": "efo",
    "experimentalFactors": "compound, dose",
    "assayCount": 128,
    "releaseLinks": "2 links",
    "releaseFiles": "2 files",

    samples: [
      {
        assayName: "sc-exp_008_skin-tel-ac7-63-1",
        organism: "Mus musculus",
        strain: "C57BL/6J",
        individual: "1151363",
        age: "17",
        timeUnit: "week",
        developmentalStage: "adult",
        sex: "female",
        genotype: "wild type",
        organismPart: "skin of body",
        disease: "normal",
        materialType: "organism part",
        libraryLayout: "PAIRED",
        librarySelection: "RANDOM",
        librarySource: "TRANSCRIPTOMIC",
        libraryStrategy: "SINGLE CELL",
        cdnaRead: "read2",
        cdnaReadOffset: "0",
        cdnaReadSize: "95",
        cellBarcodeOffset: "0",
        cellBarcodeRead: "read1",
        cellBarcodeSize: "16",
        endBias: "3 prime tag",
        inputMolecule: "polyA RNA",
        libraryConstruction: "10x 3' v3",
        primer: "oligo-dT",
        singleCellIsolation: "10x technology",
        spikeIn: "none",
        umiBarcodeOffset: "16",
        umiBarcodeRead: "read1",
        umiBarcodeSize: "12",
        performer: "DKFZ",
        technicalReplicateGroup: "group1",
        technologyType: "sequencing assay",
        enaExperiment: "ERX10138163",
        scanName: "AS-742912-LR-59094",
        submittedFileName: "AS-742912-LR-59094_R1.fastq.gz",
        enaFastq: "AS-742912-LR-59094_R1.fastq.gz",
        readType: "cell_barcode,umi_barcode",
        readIndex: "read1",
        compound: "acetone",
        dose: "100",
        doseUnit: "microliter"
      },
      {
        assayName: "sc-exp_008_skin-tel-ac7-63-2",
        organism: "Mus musculus",
        strain: "C57BL/6J",
        individual: "1151364",
        age: "17",
        timeUnit: "week",
        developmentalStage: "adult",
        sex: "female",
        genotype: "wild type",
        organismPart: "skin of body",
        disease: "normal",
        materialType: "organism part",
        libraryLayout: "PAIRED",
        librarySelection: "RANDOM",
        librarySource: "TRANSCRIPTOMIC",
        libraryStrategy: "SINGLE CELL",
        cdnaRead: "read2",
        cdnaReadOffset: "0",
        cdnaReadSize: "95",
        cellBarcodeOffset: "0",
        cellBarcodeRead: "read1",
        cellBarcodeSize: "16",
        endBias: "3 prime tag",
        inputMolecule: "polyA RNA",
        libraryConstruction: "10x 3' v3",
        primer: "oligo-dT",
        singleCellIsolation: "10x technology",
        spikeIn: "none",
        umiBarcodeOffset: "16",
        umiBarcodeRead: "read1",
        umiBarcodeSize: "12",
        performer: "DKFZ",
        technicalReplicateGroup: "group1",
        technologyType: "sequencing assay",
        enaExperiment: "ERX10138164",
        scanName: "AS-742912-LR-59095",
        submittedFileName: "AS-742912-LR-59095_R1.fastq.gz",
        enaFastq: "AS-742912-LR-59095_R1.fastq.gz",
        readType: "cell_barcode,umi_barcode",
        readIndex: "read1",
        compound: "acetone",
        dose: "100",
        doseUnit: "microliter"
      },
      {
        assayName: "sc-exp_008_skin-tel-ac7-63-1",
        organism: "Mus musculus",
        strain: "C57BL/6J",
        individual: "1151363",
        age: "17",
        timeUnit: "week",
        developmentalStage: "adult",
        sex: "female",
        genotype: "wild type",
        organismPart: "skin of body",
        disease: "normal",
        materialType: "organism part",
        libraryLayout: "PAIRED",
        librarySelection: "RANDOM",
        librarySource: "TRANSCRIPTOMIC",
        libraryStrategy: "SINGLE CELL",
        cdnaRead: "read2",
        cdnaReadOffset: "0",
        cdnaReadSize: "95",
        cellBarcodeOffset: "0",
        cellBarcodeRead: "read1",
        cellBarcodeSize: "16",
        endBias: "3 prime tag",
        inputMolecule: "polyA RNA",
        libraryConstruction: "10x 3' v3",
        primer: "oligo-dT",
        singleCellIsolation: "10x technology",
        spikeIn: "none",
        umiBarcodeOffset: "16",
        umiBarcodeRead: "read1",
        umiBarcodeSize: "12",
        performer: "DKFZ",
        technicalReplicateGroup: "group1",
        technologyType: "sequencing assay",
        enaExperiment: "ERX10138163",
        scanName: "AS-742912-LR-59094",
        submittedFileName: "AS-742912-LR-59094_R1.fastq.gz",
        enaFastq: "AS-742912-LR-59094_R1.fastq.gz",
        readType: "cell_barcode,umi_barcode",
        readIndex: "read1",
        compound: "acetone",
        dose: "100",
        doseUnit: "microliter"
      },
      {
        assayName: "sc-exp_008_skin-tel-ac7-63-1",
        organism: "Mus musculus",
        strain: "C57BL/6J",
        individual: "1151363",
        age: "17",
        timeUnit: "week",
        developmentalStage: "adult",
        sex: "female",
        genotype: "wild type",
        organismPart: "skin of body",
        disease: "normal",
        materialType: "organism part",
        libraryLayout: "PAIRED",
        librarySelection: "RANDOM",
        librarySource: "TRANSCRIPTOMIC",
        libraryStrategy: "SINGLE CELL",
        cdnaRead: "read2",
        cdnaReadOffset: "0",
        cdnaReadSize: "95",
        cellBarcodeOffset: "0",
        cellBarcodeRead: "read1",
        cellBarcodeSize: "16",
        endBias: "3 prime tag",
        inputMolecule: "polyA RNA",
        libraryConstruction: "10x 3' v3",
        primer: "oligo-dT",
        singleCellIsolation: "10x technology",
        spikeIn: "none",
        umiBarcodeOffset: "16",
        umiBarcodeRead: "read1",
        umiBarcodeSize: "12",
        performer: "DKFZ",
        technicalReplicateGroup: "group1",
        technologyType: "sequencing assay",
        enaExperiment: "ERX10138163",
        scanName: "AS-742912-LR-59094",
        submittedFileName: "AS-742912-LR-59094_R1.fastq.gz",
        enaFastq: "AS-742912-LR-59094_R1.fastq.gz",
        readType: "cell_barcode,umi_barcode",
        readIndex: "read1",
        compound: "acetone",
        dose: "100",
        doseUnit: "microliter"
      },
      {
        assayName: "sc-exp_009_liver-ac8-64-3",
        organism: "Mus musculus",
        strain: "BALB/c",
        individual: "1151365",
        age: "20",
        timeUnit: "week",
        developmentalStage: "adult",
        sex: "male",
        genotype: "mutant",
        organismPart: "liver",
        disease: "healthy",
        materialType: "organism part",
        libraryLayout: "SINGLE",
        librarySelection: "RANDOM",
        librarySource: "TRANSCRIPTOMIC",
        libraryStrategy: "SINGLE CELL",
        cdnaRead: "read1",
        cdnaReadOffset: "10",
        cdnaReadSize: "90",
        cellBarcodeOffset: "5",
        cellBarcodeRead: "read2",
        cellBarcodeSize: "15",
        endBias: "5 prime tag",
        inputMolecule: "total RNA",
        libraryConstruction: "Drop-seq",
        primer: "random hexamer",
        singleCellIsolation: "FACS",
        spikeIn: "ERCC",
        umiBarcodeOffset: "20",
        umiBarcodeRead: "read2",
        umiBarcodeSize: "10",
        performer: "Broad Institute",
        technicalReplicateGroup: "group2",
        technologyType: "sequencing assay",
        enaExperiment: "ERX10138165",
        scanName: "BS-843013-LR-60106",
        submittedFileName: "BS-843013-LR-60106_R1.fastq.gz",
        enaFastq: "BS-843013-LR-60106_R1.fastq.gz",
        readType: "cell_barcode,umi_barcode",
        readIndex: "read2",
        compound: "ethanol",
        dose: "200",
        doseUnit: "microliter"
      },
      {
        assayName: "sc-exp_010_heart-ac9-65-4",
        organism: "Rattus norvegicus",
        strain: "Sprague Dawley",
        individual: "1151366",
        age: "25",
        timeUnit: "week",
        developmentalStage: "adult",
        sex: "female",
        genotype: "transgenic",
        organismPart: "heart",
        disease: "cardiomyopathy",
        materialType: "organism part",
        libraryLayout: "PAIRED",
        librarySelection: "RANDOM",
        librarySource: "TRANSCRIPTOMIC",
        libraryStrategy: "RNA-Seq",
        cdnaRead: "read2",
        cdnaReadOffset: "0",
        cdnaReadSize: "100",
        cellBarcodeOffset: "10",
        cellBarcodeRead: "read1",
        cellBarcodeSize: "20",
        endBias: "full length",
        inputMolecule: "mRNA",
        libraryConstruction: "Smart-seq2",
        primer: "oligo-dT",
        singleCellIsolation: "microfluidics",
        spikeIn: "none",
        umiBarcodeOffset: "30",
        umiBarcodeRead: "read1",
        umiBarcodeSize: "15",
        performer: "Max Planck Institute",
        technicalReplicateGroup: "group3",
        technologyType: "sequencing assay",
        enaExperiment: "ERX10138166",
        scanName: "CS-952014-LR-61217",
        submittedFileName: "CS-952014-LR-61217_R2.fastq.gz",
        enaFastq: "CS-952014-LR-61217_R2.fastq.gz",
        readType: "cell_barcode,umi_barcode",
        readIndex: "read1",
        compound: "saline",
        dose: "50",
        doseUnit: "microliter"
      },
      {
        assayName: "sc-exp_011_brain-ac10-66-5",
        organism: "Homo sapiens",
        strain: "N/A",
        individual: "1151367",
        age: "30",
        timeUnit: "year",
        developmentalStage: "adult",
        sex: "male",
        genotype: "wild type",
        organismPart: "cerebral cortex",
        disease: "Alzheimer's",
        materialType: "organism part",
        libraryLayout: "SINGLE",
        librarySelection: "RANDOM",
        librarySource: "TRANSCRIPTOMIC",
        libraryStrategy: "RNA-Seq",
        cdnaRead: "read1",
        cdnaReadOffset: "5",
        cdnaReadSize: "85",
        cellBarcodeOffset: "0",
        cellBarcodeRead: "read2",
        cellBarcodeSize: "18",
        endBias: "5 prime tag",
        inputMolecule: "total RNA",
        libraryConstruction: "Seq-Well",
        primer: "random hexamer",
        singleCellIsolation: "nanowell",
        spikeIn: "ERCC",
        umiBarcodeOffset: "18",
        umiBarcodeRead: "read2",
        umiBarcodeSize: "10",
        performer: "Harvard University",
        technicalReplicateGroup: "group4",
        technologyType: "sequencing assay",
        enaExperiment: "ERX10138167",
        scanName: "HS-106015-LR-62328",
        submittedFileName: "HS-106015-LR-62328_R1.fastq.gz",
        enaFastq: "HS-106015-LR-62328_R1.fastq.gz",
        readType: "cell_barcode,umi_barcode",
        readIndex: "read2",
        compound: "glucose",
        dose: "150",
        doseUnit: "microliter"
      }
      
    ]

  },
  {
    "accession": "E-MTAB-12456",
    "authors": [
      "Pablo Baeza Centurion",
      "Fritjof Lammers",
      "Mikaela Behm",
      "Michaela Frye",
      "Duncan Odom",
      "Angela Goncalves"
    ],
    "title": "Single-cell RNA (10X Chromium) of mouse DMBA/TPA treated or control back skin and matched livers (2) (IKMB) 2022",
    "studyType": "RNA-seq of coding RNA from single cells",
    "organism": "Mus musculus",
    "description": "We generated single cell transcriptomes from full thickness skin biopsies in mouse to quantify the skin cell types found in this species (control samples). To study how mouse skin changes upon exposure to a carcinogen, we performed a classical two-stage skin carcinogenesis experiment, wherein cancer is initiated by a single application of 7,12-dimethylbenz[a]-anthracene (DMBA) followed by repeated treatment with 12-O-tetradecanoylphorbol-13-acetate (TPA) to drive cell proliferation. After 10 weeks, full thickness skin biopsies were collected and used to generate single cell transcriptomes (treatment samples).",
    "releaseDate": "21 November 2023",
    "samplesCount": 22,
    "technology": "Sequencing assay",
    "assayByMolecule": "RNA assay",
    "experimentalDesigns": "case control design",
    "experimentalFactors": "compound, dose",
    "assayCount": 44,
    "releaseLinks": "3 links",
    "releaseFiles": "2 files",
    samples: []
  },
  {
    "accession": "E-MTAB-13205",
    "authors": [
      "Daniela Rodrigues",
      "Klaus Eyer",
      "Olivia Bucheli"
    ],
    "title": "Single-cell RNA sequencing of mouse primary B cells to investigate subpopulation markers",
    "studyType": "RNA-seq of coding RNA from single cells",
    "organism": "Mus musculus",
    "description": "The project aims at linking functionality to metabolic fluxes of mouse primary B cells, potentially correlating antibody secretion rates with metabolic differences in subpopulations of B cells. In previous experiments, subpopulations of primary B cells with different phenotypes were observed. Therefore, the next step is to further characterize these subpopulations of B cells via single-cell RNA sequencing so that we gain insight about cell characteristics and individual gene markers, and their potential biological role. Our hypothesis is that these cells present different expression profiles of key genes and/or are relevant in different immune-related pathways.",
    "releaseDate": "20 November 2023",
    "samplesCount": 8,
    "technology": "Sequencing assay",
    "assayByMolecule": "RNA assay",
    "experimentalDesigns": "stimulus or stress design",
    "experimentalFactors": "time, organism part",
    "assayCount": 8,
    "releaseLinks": "1 link",
    "releaseFiles": "10 files",
    "releaseViews": "6 views",
    samples: []
  },
  {
    "accession": "E-MTAB-6330",
    "authors": [
      "Vaquerizas Lab",
      "Juan Vaquerizas",
      "Kai Kruse",
      "Noelia Díaz"
    ],
    "title": "Four Hi-C datasets from mESCs and 2C-like cells generated by knocking down the histone chaperone CAF-1 in mESCs",
    "studyType": "Hi-C",
    "organism": "Mus musculus",
    "description": "In this experiment, we've examined chromatin conformation of mESCs and 2C-like cells generated from a CAF-1 knockdown. The method to generate the knockdown was described in (). We performed a modified in situ Hi-C protocol from (Rao et al., 2014) and that can be found in detail at (Díaz et al., 2017, under revision). Samples were digested with MboI restriction enzyme having as starting material 100k cells with two biological replicates per sampling point. The aim of the experiment was to analyze the potential chromatin conformational changes that accompany the mESC to 2C-like transition.",
    "releaseDate": "16 November 2023",
    "samplesCount": 4,
    "technology": "Sequencing assay",
    "assayByMolecule": "DNA assay",
    "experimentalDesigns": "cell type comparison design, development or differentiation design",
    "experimentalFactors": "cell type",
    "assayCount": 4,
    "releaseLinks": "1 link",
    "releaseFiles": "14 files",
    samples: []
  },
  {
    "accession": "E-MTAB-13468",
    "authors": [
      "Charles Girardot",
      "Marzia Munafo"
    ],
    "title": "RNAseq of setd2KO mESC",
    "studyType": "RNA-seq of coding RNA",
    "organism": "Mus musculus",
    "description": "Total (rRNA-depleted) RNAseq of mouse ESCs carrying a homozygous KO mutation in setd2. Homozygous cells were also treated with the DNA methylation inhibitor 5-azacytidine. Total RNA was isolated from cell pellets using NEB Monarch® Total RNA Miniprep Kit and rRNA removed with NEBNext® rRNA Depletion Kit v2 (Human/Mouse/Rat). Libraries were prepared using NEBNext® Ultra™ II Directional RNA Library Prep Kit for Illumina®  (NEB E7760L, input: 500 ng of total RNA). Libraries were multiplexed and sequenced on a NextSeq500 (Paired-End; read length 40). Each sample is present in 3 biological replicates.",
    "releaseDate": "15 November 2023",
    "samplesCount": 9,
    "technology": "Sequencing assay",
    "assayByMolecule": "RNA assay",
    "experimentalDesigns": "biological replicate efo, genotype design efo, compound treatment design efo",
    "experimentalFactors": "compound, genotype, dose",
    "assayCount": 1,
    "releaseLinks": "1 link",
    "releaseFiles": "2 files",
    samples: []
  },
  {
    "accession": "E-MTAB-13467",
    "authors": [
      "Charles Girardot",
      "Cristina Policarpi"
    ],
    "title": "RNAseq of mll2wt and mll2[Y2602A] mESC and EpiLC",
    "studyType": "RNA-seq of coding RNA",
    "organism": "Mus musculus",
    "description": "PolyA RNAseq of mouse ESCs and EpiLCs carrying a homozygous point mutation in the catalytic domain of mll2[Y2602A]. Total RNA was isolated from cell pellets using NEB Monarch Total RNA Miniprep Kit and libraries prepared using NEBNext RNA Ultra II kit (NEB E7770S, input: 350 ng of total RNA). Libraries were multiplexed and sequenced on a NextSeq500 (Paired-End; read length 40). Each sample is present in 3 biological replicates.",
    "releaseDate": "15 November 2023",
    "samplesCount": 12,
    "technology": "Sequencing assay",
    "assayByMolecule": "RNA assay",
    "experimentalDesigns": "biological replicate efo, cell type comparison design efo, genotype design efo",
    "experimentalFactors": "cell type, genotype",
    "assayCount": 1,
    "releaseLinks": "1 link",
    "releaseFiles": "2 files",
    samples: []
    
  },
  {
    "accession": "E-MTAB-13466",
    "authors": [
      "Charles Girardot",
      "Cristina Policarpi"
    ],
    "title": "CUT&RUN-seq of H3K4me3, H3K27me3 and H3K27ac in mll2wt and mll2[Y2602A] mESC",
    "studyType": "CUT&RUN",
    "organism": "Mus musculus",
    "description": "CUT&RUN-seq of H3K4me3, H3K27me3 and H3K27ac in mouse ESCs carrying a homozygous point mutation in the catalytic domain of mll2[Y2602A]. CUT&RUN was performed according to Skene & Henikoff, 2017 and purified DNA was used for library preparation with NEBNext DNA Ultra II kit (NEB E7645S; input: 5 ng of DNA). Libraries were multiplexed and sequenced on a NextSeq500 (Paired-End; read length 40). Each sample is present in 3 biological replicates.",
    "releaseDate": "15 November 2023",
    "samplesCount": 18,
    "technology": "Sequencing assay",
    "assayByMolecule": "DNA assay",
    "experimentalDesigns": "biological replicate efo, binding site identification design efo, genotype design efo",
    "experimentalFactors": "immunoprecipitate, genotype",
    "assayCount": 1,
    "releaseLinks": "1 link",
    "releaseFiles": "2 files",
    samples: []

  },
  {
    "accession": "E-MTAB-10033",
    "authors": [
      "Charles Girardot",
      "Ayele Denboba",
      "James Hackett"
    ],
    "title": "DNA methylation profiles of mouse sperm in response to antibiotic-induced gut microbiota dysbiosis using whole-genome bisulfite sequencing",
    "studyType": "Bisulfite-seq",
    "organism": "Mus musculus",
    "description": "DNA methylation profile of mouse sperm from conventionally-raised mice and gut dysbiosis experienced mice were characterized using whole-genome bisulfite sequencing. Genome-wide DNA methylation changes between control and dysbiotic male’s sperm were highly comparable, with no change in DNAme globally or at genomic features, only 21 differentially methylated regions (DMR) were identified, which did not overlap known regulatory elements. Epididymal sperm samples were harvested from 11 weeks old inbred male mice that were experiencing gut microbiota dysbiosis for 6-week (antibiotics treated, n=5), or drink sterilized water (control, n=5).",
    "releaseDate": "13 November 2023",
    "samplesCount": 10,
    "technology": "Sequencing assay",
    "assayByMolecule": "DNA assay",
    "experimentalDesigns": "replicate design, compound treatment design",
    "experimentalFactors": "stimulus, phenotype",
    "assayCount": 5,
    "releaseLinks": "1 link",
    "releaseFiles": "2 files",
    samples: []
  },
  {
    "accession": "E-MTAB-10273",
    "authors": [
      "Charles Girardot",
      "Ayele Denboba",
      "James Hackett"
    ],
    "title": "Genomic profiling of offspring liver tissue in response to paternal gut microbiota dysbiosis using whole genome sequencing",
    "studyType": "DNA-seq",
    "organism": "Mus musculus",
    "description": "Liver tissue samples were harvested from offspring sired by conventionally-raised male mice or dysbiotic sire, and profiled for genome changes using whole genome sequencing. F1 offspring samples were collected from six independent mating, and gDNA was extracted from offspring liver at postnatal day P17.",
    "releaseDate": "13 November 2023",
    "samplesCount": 6,
    "technology": "Sequencing assay",
    "assayByMolecule": "DNA assay", 
    "experimentalDesigns": "replicate design, compound treatment design",
    "experimentalFactors": "treatment, phenotype" ,
    "assayCount": 18,
    "releaseLinks": "1 link",
    "releaseFiles": "2 files",
    samples: []

  },
  {
    "accession": "E-MTAB-10034",
    "authors": [
      "Charles Girardot",
      "Ayele Denboba",
      "James Hackett"
    ],
    "title": "Transcriptome profiles of paternal testis and their offspring in response to gut microbiota dysbiosis using RNA sequencing analysis",
    "studyType": "RNA-seq of total RNA",
    "organism": "Mus musculus",
    "description": "Tissue samples harvested from conventionally-raised sire and their offspring or dysbiotic sire and their offspring were profiled for transcriptome changes using total RNA sequencing. Total RNA was extracted from four different tissue types: sire testis, F1 placenta (at E13.5 & E18.5), and F1 brain and brown adipose tissue (at postnatal day P17). Testis were harvested from 11-weeks inbred male mice that were experiencing gut microbiota dysbiosis for 6-week (antibiotics treated, n=5), or drink sterilized water (control, n=5). While, F1 offspring samples were collected from three independent matings per group and two offspring samples per litter.",
    "releaseDate": "13 November 2023",
    "samplesCount": 65,
    "technology": "Sequencing assay",
    "assayByMolecule": "RNA assay",
    "experimentalDesigns": "replicate design, compound treatment design, development or differentiation design, organism part comparison design",
    "experimentalFactors": "generation, age, organism part, stimulus, phenotype",

    "assayCount": 3,
    "releaseLinks": "1 link",
    "releaseFiles": "2 files",
    "releaseViews": "8 views",
    samples: []

  },
  {
    "accession": "E-MTAB-12433",
    "authors": [
      "Miltiadis Tsesmelis"
    ],
    "title": "RNA-seq of mouse Pancreatic Intraepithelial Neoplasias (PanINs) with NF-κB Essential Modulator (NEMO) knockout against NEMO wild-type",
    "studyType": "RNA-seq of total RNA",
    "organism": "Mus musculus",
    "description": "The canonical NF-κB pathway is active in 70% of all pancreatic cancer cases and NF-κB Essential Modulator (NEMO) is essential for the activation of this pathway. In our study, we used KC mice, which express the oncogenic KRAS and develop precancerous lesions termed Pancreatic Intraepithelial Neoplasias (PanINs), and KNeC mice, which express the oncogenic KRAS and have NEMO deleted in their pancreatic cells. These mice were injected with cerulein to promote the development of pancreatitis (cerulein dosage= 50μg/kg). Cerulein was injected at 8 hourly intervals for 2 days in total. The first injection day was when mice reached their sixth week of age and the second injection day was 3 days after the first injection day. Both KC and KNeC mice developed PanINs. At the age of 10 months, pancreata of KC and KNeC mice were analyzed. Using laser capture microdissection, PanINs from both groups were excised and their transcriptome was analyzed though RNA-seq.",
    "releaseDate": "9 November 2023",
    "samplesCount": 6,
    "technology": "Sequencing assay",
    "assayByMolecule": "RNA assay",
    "experimentalDesigns": "genetic modification design, genotype design, disease state design",
    "experimentalFactors": "genotype",
    "assayCount": 18,
    "releaseLinks": "1 link",
    "releaseFiles": "10 files",
    "releaseViews": "1 view",
    samples: []
  },
  {
    "accession": "E-MTAB-12560",
    "authors": [
      "Peter Tessarz"
    ],
    "title": "scATAC-seq of mouse liver tissue derived from young and old mice II",
    "studyType": "scATAC-seq",
    "organism": "Mus musculus",
    "description": "We investigate if the differences in phenotype and transcriptome over age might be explained by an underlying change on the epigenetic level. We performed single-cell ATAC sequencing using the 10x Chromium platform. We profiled 2259 nuclei prepared from 3 young liver tissues and 2490 nuclei from 3 old liver tissues. Publication Nikopoulou C, Kleinenkuhnen N, Parekh S, Sandoval T, Ziegenhain C, Schneider F, Giavalisco P, Donahue KF, Vesting AJ, Kirchner M, Bozukova M, Vossen C, Altmüller J, Wunderlich T, Sandberg R, Kondylis V, Tresch A, Tessarz P. (2023). Spatial and single-cell profiling of the metabolome, transcriptome and epigenome of the aging mouse liver. Volume 3. Issue 11. pmid 37946043.",
    "releaseDate": "9 November 2023",
    "samplesCount": 2,
    "technology": "Sequencing assay",
    "assayByMolecule": "DNA assay",
    "experimentalDesigns": "case control design",
    "experimentalFactors": "phenotype",
    "assayCount": 4,
    "releaseLinks": "1 link",
    "releaseFiles": "2 files",
    "releaseViews": "10 views",
    samples: []
  },
  {
    "accession": "E-MTAB-12414",
    "authors": [
      "Nicholas Ilott",
      "Kevin Maloy"
    ],
    "title": "MHC class II antigen presentation by intestinal epithelial cells fine-tunes bacteria-reactive CD4 T cell responses",
    "studyType": "RNA-seq of coding RNA",
    "organism": "Mus musculus",
    "description": "Intestinal organoids stimulated with conditioned media from inflamed or non-inflamed source.",
    "releaseDate": "9 November 2023",
    "samplesCount": 12,
    "technology": "Sequencing assay",
    "assayByMolecule": "RNA assay",
    "experimentalDesigns": "stimulus or stress design",
    "experimentalFactors": "stimulus",
    "assayCount": 24,
    "releaseLinks": "1 link",
    "releaseFiles": "2 files",
    samples: []
  },
  {
    "accession": "E-MTAB-6414",
    "authors": [
      "Christian Schwager",
      "Cheng Zhou"
    ],
    "title": "Transcriptome analysis of molecular mechanism in inhibition of x-ray or carbon-ion induced lung fibrosis by Fc-Endostatin and its derived peptides",
    "studyType": "transcription profiling by array",
    "organism": "Mus musculus",
    "description": "Endostatin is a naturally occurring 183-amino acid proteolytic fragment of collagen XVIII that localizes in the basement membrane around blood vessels. The anti-tumor properties of this protein have been extensively described, demarcating endostatin as an endogenous inhibitor of angiogenesis. Further, it suppresses many signaling cascades such as pro-inflammatory NF-κB, coagulation, and adhesion cascades. Yamaguchi et al. reported that endostatin via its C-terminal domain (E4 peptide) has elicited anti-fibrosis effects. However, the zinc-binding domain has been previously confined to the N terminus (endostatin mP1 peptide) and was critical to numerous functions of the molecule. The present study aimed to better understand the impact of oligomerization (Fc-Endostatin) as well as N- vs. C-terminal fragments of endostatin (mP1, CE4) on modulating radiation-induced lung fibrosis. Mice were treated with Fc-endostatin (Fc-Endo), N-terminus endostatin peptide (mP1), or C-terminus endostatin E4 peptide (CE4) combined with photon 20 Gy or carbon-ions 12.5 Gy whole thoracic irradiation.",
    "releaseDate": "9 November 2023",
    "samplesCount": 43,
    "technology": "Array assay",
    "assayByMolecule": "RNA assay",
    "experimentalDesigns": "compound treatment design",
    "experimentalFactors": "irradiate, compound, dose",
    "assayCount": 43,
    "releaseLinks": "2 links",
    "releaseFiles": "45 files",
    samples: []
  },
  {
    "accession": "E-MTAB-6420",
    "authors": [
      "Cheng Zhou",
      "Christian Schwager"
    ],
    "title": "Transcriptome analysis to decipher molecular mechanism in early lung toxicity induced by low-LET photon and high-LET carbon-ions in mouse model",
    "studyType": "transcription profiling by array",
    "organism": "Mus musculus",
    "description": "The time factor in the development of radiation-induced lung fibrosis is important but not well characterized so far. This study was to investigate the time series of acute-, subacute-, early, and late- timepoints after exposure with low-LET photons versus proton versus and high-LET carbon-ions. The role of CTGF inhibitor in modulating inflammation-related signaling pathways were also studied at the acute timepoints. The potential mechanisms underlying the time-dependent progression of inflammatory and fibrotic response is to be illustrated in the present study.",
    "releaseDate": "9 November 2023",
    "samplesCount": 51,
    "technology": "Array assay",
    "assayByMolecule": "RNA assay",
    "experimentalDesigns": "time series design",
    "experimentalFactors": "time, irradiate, dose, compound",
    "assayCount": 51,
    "releaseLinks": "1 link",
    "releaseFiles": "53 files",
    samples: []
  },
  {
    "accession": "E-MTAB-6419",
    "authors": [
      "Christian Schwager",
      "Cheng Zhou"
    ],
    "title": "Transcriptome analysis to decipher molecular mechanism in radiation-induced lung fibrosis in DNA-PKcs knockout mouse model",
    "studyType": "transcription profiling by array",
    "organism": "Mus musculus",
    "description": "The potential mechanisms of DNA-PKcs and its related signaling pathways in radiation-induced pulmonary toxicity are unclear. The current study utilized a genetic engineering DNA-PKcs knockout mouse model, to investigate the molecular mechanisms after dose-response exposure of the fractionated low-LET photon and high-LET carbon-ion exposure to the whole thorax.",
    "releaseDate": "9 November 2023",
    "samplesCount": 21,
    "technology": "Array assay",
    "assayByMolecule": "RNA assay",
    "experimentalDesigns": "dose response design",
    "experimentalFactors": "dose, irradiate",
    "assayCount": 21,
    "releaseLinks": "1 link",
    "releaseFiles": "23 files",
    "releaseViews": "1 view",
    samples: []
  },
  {
    "accession": "E-MTAB-6409",
    "authors": [
      "Christian Schwager",
      "Cheng Zhou"
    ],
    "title": "Transcriptome analysis to decipher molecular mechanism governing single fraction photon and carbon ions induced lung fibrosis in mouse models",
    "studyType": "transcription profiling by array",
    "organism": "Mus musculus",
    "description": "Normal lung tissue tolerance constitutes a limiting factor in delivering the required dose of radiotherapy to cure thoracic and chest wall malignancies. Patient genetic predisposition, the volume of irradiated lung and combination regimens consisting of concurrent chemotherapy are correlated with increased risk of radiation-induced toxicity in lung. The main purpose of this study is to investigate dose-response regulations of mouse lung irradiation based on a comprehensive dose-escalation program, for a better understanding of the molecular mechanism governing radiation-induced lung fibrosis by high-LET carbon-ions versus conventional low-LET X-ray.",
    "releaseDate": "8 November 2023",
    "samplesCount": 55,
    "technology": "Array assay",
    "assayByMolecule": "RNA assay",
    "experimentalDesigns": "injury design, dose response design",
    "experimentalFactors": "irradiate, dose, injury, time",
    "assayCount": 55,
    "releaseLinks": "2 links",
    "releaseFiles": "57 files",
    samples: []
  },
  {
    "accession": "E-MTAB-11197",
    "authors": [
      "Lisa Zerad"
    ],
    "title": "RNAseq of sciatic nerve from WT versus Adar1cKO mice",
    "releaseDate": "3 November 2023",
    "studyType": "RNA-seq of coding RNA",
    "organism": "Mus musculus",
    "description": "Identification of deregulated transcripts in sciatic nerves of Adar1cKO mice versus WT to identify the origin of myelin defects observed upon invalidation of ADAR1 in neural crest cells.",
    "samplesCount": 6,
    "technology": "Sequencing assay",
    "assayByMolecule": "RNA assay",
    "experimentalDesigns": "genotype design",
    "experimentalFactors": "genotype",
    "assayCount": 12,
    "releaseLinks": "1 link",
    "releaseFiles": "2 files",
    "releaseViews": "19 views",
    samples: []
  },
      {
      "accession": "S-EPMC3208355",
      "releaseDate": "1 January 2011",
      "title": "jTraML: an open source Java API for TraML, the PSI standard for sharing SRM transitions.",
      "authors": [ ],
      "studyType": "RNA-seq of coding RNA",
      "organism": "Mus musculus",
      "description": "Identification of deregulated transcripts in sciatic nerves of Adar1cKO mice versus WT to identify the origin of myelin defects observed upon invalidation of ADAR1 in neural crest cells.",
      "samplesCount": 6,
      "technology": "Sequencing assay",
      "assayByMolecule": "RNA assay",
      "experimentalDesigns": "genotype design",
      "experimentalFactors": "genotype",
      "assayCount": 12,
      "releaseLinks": "1 link",
      "releaseFiles": "2 files",
      "releaseViews": "19 views",
      samples: []
    },
    {
      accession: "S-EPMC161810",
      "authors": [ ],
      "studyType": "RNA-seq of coding RNA",
      "organism": "Mus musculus",
      "samplesCount": 6,
      "technology": "Sequencing assay",
      "assayByMolecule": "RNA assay",
      "experimentalDesigns": "genotype design",
      "experimentalFactors": "genotype",
      "assayCount": 12,
      releaseDate: "1 January 2003",
      releaseLinks: "3 links",
      releaseFiles: "3 files",
      releaseViews: "4 views",
      title: "A markup language for electrocardiogram data acquisition and analysis (ecgML).",
      description: "and Mathematics, University of Ulster, Newtownabbey, BT0QB, Co. Antrim, Northern Ireland, U.K 1472-6947-3-4-S1.dtd 1472-6947-3-4-S2.xsd 1472-6947-3-4-S3.xml 10.1186/1472-6947-3-4 PMC161810 12735790",
      samples: []
    },
    {
      accession: "S-EPMC1184081",
      releaseDate: "1 January 2005",
      "authors": [ ],
      "studyType": "RNA-seq of coding RNA",
      "organism": "Mus musculus",
      "samplesCount": 6,
      "technology": "Sequencing assay",
      "assayByMolecule": "RNA assay",
      "experimentalDesigns": "genotype design",
      "experimentalFactors": "genotype",
      "assayCount": 12,
      releaseLinks: "3 links",
      releaseFiles: "3 files",
      releaseViews: "22 views",
      title: "Distribution of immunodeficiency fact files with XML--from Web to WAP.",
      description: "Technology, FI-University of Tampere, Finland Research Unit, Tampere University Hospital, FI-Tampere, Finland 1472-6947-5-21-S1.xsd 1472-6947-5-21-S2.dtd 1472-6947-5-21-S3.xml 10.1186/1472-6947-5-21 PMC1184081 15978138",
      samples: []
    },
    {
      accession: "S-EPMC3895879",
      releaseDate: "1 January 2014",
      releaseLinks: "3 links",
      releaseFiles: "1 file",
      title: "Multiscale deconstruction of molecular architecture in corn stover.",
      description: "/CA CAT, XSD, Advanced Photon Source, Argonne National Laboratory, Argonne, IL 60439. National Synchrotron Light Source, Brookhaven National Laboratory, Upton, NY 11973. X-ray Science Division, Advanced Photon Source, Argonne National Laboratory, Argonne, IL 60439. srep03756-s1.doc 10.1038/srep03756 PMC3895879 24441444",
      "authors": [ ],
      "studyType": "RNA-seq of coding RNA",
      "organism": "Mus musculus",
      "samplesCount": 6,
      "technology": "Sequencing assay",
      "assayByMolecule": "RNA assay",
      "experimentalDesigns": "genotype design",
      "experimentalFactors": "genotype",
      "assayCount": 12,
      samples: []
    },
]